#!/usr/bin/env python
import os
import array

read_file = open('hitlist.txt','r')


for domains in read_file:
	print('================http probing================')
	os.system("echo " + domains.rstrip() + " | ~/go/bin/httprobe")
	print('================http linking================')
	print('https://' + domains.rstrip() + '/v1/')
	print('https://' + domains.rstrip() + '/v2/')
	print('https://' + domains.rstrip() + '/v3/')
	print('https://' + domains.rstrip() + '/v4/')
	print('https://' + domains.rstrip() + '/v5/')
	print('https://' + domains.rstrip() + '/v6/')
	print('https://' + domains.rstrip() + '/auth/')
	print('https://' + domains.rstrip() + '/graphql')
	print('https://' + domains.rstrip() + '/gists/')
	print('https://' + domains.rstrip() + '/repos/')
	print('https://' + domains.rstrip() + '/admin/')
	print('https://' + domains.rstrip() + '/applications/')
	print('https://' + domains.rstrip() + '/authorizations/')
	print('https://' + domains.rstrip() + '/repos/')
	print('https://' + domains.rstrip() + '/user/')
	print('https://' + domains.rstrip() + '/users/')
	print('https://' + domains.rstrip() + '/users/keys/')
	print('https://' + domains.rstrip() + '/app/')
	print('https://' + domains.rstrip() + '/apps/')
	print('https://' + domains.rstrip() + '/authorizations/')
	print('https://' + domains.rstrip() + '/setup/api/settings')
	print('https://' + domains.rstrip() + '/setup/api/settings/authorized-keys')
	print('https://' + domains.rstrip() + '/setup/api/configcheck/')
	print('https://' + domains.rstrip() + '/v2/scim')
	print('https://' + domains.rstrip() + '/installations/')
	print('https://' + domains.rstrip() + '/projects/')
	print('https://' + domains.rstrip() + '/meta/')
	print('https://' + domains.rstrip() + '/oauth_authorizations/')
read_file.close()
